export enum EventNamesEnum {
  SIGN_IN = 'signin',
  SIGN_OUT = 'signout',
  SIGN_UP = 'signup',
  NEW_PROPERTY_SUBSCRIPTION = 'new_property_subscription',
  TRIGGER_REMOTE_MODAL_LGA = 'trigger_remote_modal_lga',
  TRIGGER_REMOTE_MODAL_LGA_WARD = 'trigger_remote_modal_lga_ward',
  // RESET_PASSWORD = '<PASSWORD>',
  // RESET_PASSWORD_CONFIRM = '<PASSWORD>',
  // CHANGE_PASSWORD = '<PASSWORD>',
  // CHANGE_EMAIL = 'change_email',
  // CHANGE_PROFILE = 'change_profile',
  // CHANGE_PROFILE_PICTURE = 'change_profile_picture',
  // CHANGE_PROFILE_COVER_PICTURE = 'change_profile_cover_picture',
  // CHANGE_PROFILE_PASSWORD = '<PASSWORD>',
  // CHANGE_PROFILE_EMAIL = 'change_profile_email',
  // CHANGE_PROFILE_FIRST_NAME = 'change_profile_first_name',
  // CHANGE_PROFILE_LAST_NAME = 'change_profile_last_name',
  // CHANGE_PROFILE_MIDDLE_NAME = 'change_profile_middle_name',
  // CHANGE_PROFILE_COMPANY_NAME = 'change_profile_company_name',
  // CHANGE_PROFILE_COMPANY_WEBSITE = 'change_profile_company_website',
  // CHANGE_PROFILE_COMPANY_ADDRESS = 'change_profile_company_address',
  // CHANGE_PROFILE_COMPANY_CITY = 'change_profile_company_city',
}
